[package]
name = "thought-capturer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
clap = "4.1.10"
csv = "1.2.1"
serde = "1.0.157"
